-- Generated by Ryoku Settings (Super + ,). Lives in the user_edits overlay,
-- overwritten on every change, so change it in the GUI, not by hand. Loaded
-- after Ryoku's defaults and before your user.lua, which still wins.

hl.config({
  general = { gaps_in = 4, gaps_out = 6, border_size = 1, layout = "scrolling", gaps_workspaces = 16 },
  decoration = { rounding = 6, inactive_opacity = 0.9, dim_inactive = true, dim_strength = 0.2, blur = { enabled = false, passes = 2, xray = true, popups = true }, shadow = { enabled = false } },
  input = { kb_layout = "us,br", kb_variant = "", kb_options = "grp:alt_shift_toggle", sensitivity = 0.1, accel_profile = "flat", repeat_rate = 20, repeat_delay = 250, touchpad = { tap_to_click = false, tap_and_drag = false, disable_while_typing = false } },
})

hl.animation({ leaf = "windowsIn", enabled = true, speed = 3.8, bezier = "ryokuBloom", style = "gnomed" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 2.4, bezier = "ryokuSettle", style = "gnomed" })
do
  local ok, wc = pcall(dofile, os.getenv("HOME") .. "/.cache/ryoku/hypr-colors.lua")
  local function rgb(h, f) if type(h) ~= "string" then h = f end return "rgb(" .. h:gsub("#", "") .. ")" end
  hl.config({ general = { ["col.active_border"] = { colors = { rgb(ok and wc and wc.active, "#e0563b"), rgb(ok and wc and wc.inactive, "#313a4d") }, angle = 45 } } })
end
hl.animation({ leaf = "borderangle", enabled = true, speed = 50.0, bezier = "linear", style = "loop" })
hl.curve("almostLinear", { type = "bezier", points = { { 0.34, 1.5 }, { 0.64, 1.0 } } })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 2.2, bezier = "almostLinear" })

hl.env("XCURSOR_THEME", "Bibata-Material-Ryoku")
hl.env("XCURSOR_SIZE", "20")
hl.env("HYPRCURSOR_THEME", "Bibata-Material-Ryoku")
hl.env("HYPRCURSOR_SIZE", "20")

hl.env("BROWSER", "zen-beta --name zen-beta")

hl.window_rule({ name = "ryoku-tame-maximize-on-open", match = { class = ".*" }, suppress_event = "maximize" })
hl.window_rule({ name = "ryoku-user-1", match = { title = "Discord" }, maximize = true })
hl.window_rule({ name = "ryoku-user-2", match = { title = "Zen" }, maximize = true })
hl.window_rule({ name = "ryoku-user-3", match = { class = "discord-canary" }, workspace = "2" })
hl.window_rule({ name = "ryoku-user-4", match = { title = "Ryotunes" }, workspace = "3" })
hl.window_rule({ name = "ryoku-user-5", match = { title = "Sober" }, workspace = "1" })
hl.window_rule({ name = "ryoku-user-6", match = { title = "Brave" }, maximize = true })
hl.window_rule({ name = "ryoku-user-7", match = { title = "Vivaldi" }, maximize = true })
hl.config({ input = { follow_mouse = 1 } })


hl.on("hyprland.start", function()
  hl.exec_cmd("hyprctl setcursor Bibata-Material-Ryoku 20")
  hl.exec_cmd("easyeffects --hide-window --service-mode")
  hl.exec_cmd("gsr-ui")
end)
