background_opacity 0.85
#background #1e2122
font_family Iosevka Nerd Font Mono

# ==========================
# Keybinds
# ==========================

map ctrl+equal change_font_size all +2
map ctrl+minus change_font_size all -2

map ctrl+left previous_tab
map ctrl+right next_tab
map ctrl+t new_tab
map ctrl+w close_tab
